# Funding options for Trishul-SNMP
# These links will appear in the "Sponsor" button on GitHub

# GitHub Sponsors
github: tosumitdhaka

# Other platforms (uncomment and add your username when ready)
# patreon: your-patreon-username
# open_collective: your-collective-name
# ko_fi: your-kofi-username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# lfx_crowdfunding: project-name

# Custom links (Buy Me a Coffee, PayPal, etc.)
custom: ['https://buymeacoffee.com/tosumitdhaka']
